load_module modules/ngx_otel_module.so;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # Exporta traces para o OTel Collector (VM 100 em homelab ou localhost em dev)
    otel_exporter {
        endpoint 192.168.18.152:4317;
    }

    log_format main '$remote_addr - "$request" $status $body_bytes_sent';
    access_log /var/log/nginx/access.log main;

    server {
        listen 80;
        server_name localhost;

        otel_trace        on;
        otel_service_name "luiscruz.com.br";
        otel_trace_context propagate;

        root  /usr/share/nginx/html;
        index index.html;

        # Endpoint para nginx-prometheus-exporter
        location = /stub_status {
            stub_status;
            allow 127.0.0.1;
            allow 172.0.0.0/8;
            deny  all;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
